CREATE TABLE IF NOT EXISTS cars (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(150) NOT NULL,
	model VARCHAR(150) NOT NULL,
	brand VARCHAR(128) NOT NULL,
	year VARCHAR(5) NOT NULL,
	price DECIMAL(10, 2) DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);